apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
  namespace: devfile-sample-go-basic
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: devfile-sample-go-basic
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: devfile-sample-go-basic
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: devfile-sample-go-basic-
      labels:
        build.appstudio.openshift.io/application: devfile-sample-go-basic
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: devfile-sample-go-basic
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: devfile-sample-go-basic
    spec:
      params:
      - name: git-url
        value: https://github.com/devfile-samples/devfile-sample-go-basic
      - name: output-image
        value: quay.io/jduimovich0/devfile-sample-go-basic:latest-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:5cc4c4afd4c28d8918975b29312e03d623492538
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: devfile-sample-go-basic/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
